### PR TITLE
Fix NGINX loading

### PR DESCRIPTION
**Pull request by Daemo00**
Otherwise the following happens:
```
AttributeError: 'ir.ui.view' object has no attribute… 'render_template'
```

### CODE REVIEW

**Comment by Xavier-Do** [comment]
Hello Thanks for your contribution, it looks like we may have misted that.

FYI, this 14.0 is still a wip, the frontend is still broken and we didn't take the time to test in depth. It isn't adviced to use it for now.

Your commit is a valid, but can you please follow the commit "guidelines" for the subject? 

**[FIX] runbot: subject**

**Comment by Daemo00** [comment]
Thanks for the suggestion, commit renamed.

I assumed `14.0` to be a stable branch, so is `13.0` the latest stable?
Or what else is used in https://runbot.odoo.com/?

I was using the 'old' runbot interface but I'd like to upgrade it.

**Comment by Xavier-Do** [comment]
Runbot.odoo.com is using 13.0. 14.0 is a wip, and should be finalized and deployed in a few days/weeks. I'm currently experimenting with owl to speed up the main page loading, and we still need to test and cleanup the upgrade process.

**Comment by Xavier-Do** [comment]
Since I'm forcepushing the 14.0 branch this pr would need regular rebase. I cherry picked your commit in my branch ;)

**Pull request closed without merging**
