### PR TITLE
[IMP] runbot: replace clock by moon icon

### PR DESCRIPTION
**Pull request by mart-e**
For scheduled build
While schedule can be at any time, it typically runs during the night, hence the moon

screenshot_2018-08-13 runbot repo

```shell
$ sed -i 's|fa-clock-o|fa-moon-o|g' runbot/*/*.xml
```

### CODE REVIEW

**Comment by mart-e** [comment]
@d-fence r+ !

**Comment by d-fence** [comment]
seen

**Comment by d-fence** [comment]
ci

**Comment by d-fence** [comment]
merging

**Comment by d-fence** [comment]
merged

**Comment by mart-e** [comment]
Thanks robostophe !

**Pull request merged**
