### PR TITLE
[FIX] runbot.bundle compute base_id

### PR DESCRIPTION
**Pull request by gurneyalex**
the matching done on the bundle name was fragile:

* PR comming from clones have a prefix before the branch name
* Some PR can use a slightly different nameing convention (e.g. forget
the ".0" in the version number, use a different separator than '-'
* we should try really hard to find a good version, and using the target
branch name as a fallback sounds like a good idea

### CODE REVIEW

**Comment by gurneyalex** [comment]
This may be the cause for the issue I try to tackle in #423

**Comment by gurneyalex** [comment]
unfortunately I cannot check the CI failure (403 - Unauthorized)

**Comment by Xavier-Do** [comment]
Sorry for the long response time, I'll try to follow this one. 

Here is the error message

2021-01-03 07:44:47,585 32 INFO 5592420-13-0-runbot_coverage odoo.modules.loading: loading runbot/data/runbot_data.xml 
2021-01-03 07:44:47,626 32 WARNING 5592420-13-0-runbot_coverage odoo.addons.runbot.models.bundle: Could not guess the branch_id of bundle Dummy. Checking the target branch 

I didn't really took the time to understand the cause of the problem yet at first glance this fix looks a little too complex:

I may be missing something but it looks like you are not using `bundle_name`?

> PR comming from clones have a prefix before the branch name

This should be managed correctly by runbot, they are considered external pr and the target_branch_name may be used by compute_bundle_id to define the base when creating a new bundle for this pr.

> Some PR can use a slightly different nameing convention (e.g. forget  the ".0" in the version number, use a different separator than '-'

Runbot asks for strict convention when naming branches in guidelines. Runbot is based on this guideline and prefers to fail that trying to guess. This is a good way to enforce this convention.Anyway, if no base is found master will be used by default and can be changed manually on a bundle by setting "defined_base_id" if needed to avoid to create a new branch.

> we should try really hard to find a good version, and using the target branch name as a fallback sounds like a good idea

Yes it is, but most of the time when the target repo of the pr is known by runbot, the bundle should already exists since the branch is created before the pr. If not, the base_id is set manually by _compute_bundle_id (defined_base_id) since it isn't the default branch name case. This part is quite dirty and could be improved but we need to think about all cases (creation order, retarget, manual choice, ...)

**Comment by Xavier-Do** [comment]
Making some cleanup in the old forgotten pull request but this won't be merged:

This is not compatible with existing and future changes, we want to enforce a precise branch naming. External branches works fine with pr (using target).

Usually if something does not go well to define the base in my experience, it is because the base does not exist in the repo. Other issue where fixed in the past, like a very old commit on a base branch, no master branch at all, ....

**Pull request closed without merging**
