### PR TITLE
[FIX] runbot_merge: fix forward-port Odoo wiki link

### PR DESCRIPTION
**Pull request by d-fence**

### CODE REVIEW

**Comment by xmo-odoo** [comment]
@d-fence did someone un-rename this page?

**Comment by d-fence** [comment]
I duno. It was reported that the link was broken.

**Comment by xmo-odoo** [comment]
Looks like it was @mart-e

**Comment by mart-e** [comment]
Yes because @rim-odoo broke links by renaming the page before, just restored the good old way

**Comment by rim-odoo** [comment]
sorry guys ><

**Comment by xmo-odoo** [comment]
@mart-e yeah but we'd fixed everything to match so you just broke it a second time.

**Pull request merged**
