### PR TITLE
[IMP] runbot: more human time display

### PR DESCRIPTION
**Pull request by KangOl**
Wait 2 unit before change.

42s ... 60s ... 119s 2m ... 60m ... 119m 2h ... 24h ... 47h 2d ...

### CODE REVIEW

**Comment by Xavier-Do** [comment]
Approve the idea but I think we could always show two units instead. Some build are already arround two hours. What fo you think?

**Comment by KangOl** [comment]
I thought about it but the display would be weird. `1h 4m` doesn't look right and is difficult to read.

We can maybe tolerate a little more that 2 units: `delay * 2.1`

**Comment by Xavier-Do** [comment]
Or *10 to be consistent, and remove the unit for "decimals"
10h
9h01
1h01
59m
10m
9m59
1m01
59s
2s(59?)

**Comment by xmo-odoo** [comment]
Why not use `babel.dates.format_timedelta`? It already supports rollover thresholds & minimal granularities e.g. `format_timedelta(xxx, granularity='minute', threshold=2.1)`.

**Comment by KangOl** [comment]
format_timedelta is a great alternative. We can even keep the same format with `format='narrow'`

**Comment by KangOl** [comment]
Can it be merged and deployed?

**Pull request merged**
